
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'#'$(Parameters.RestoreBuildProjects)'

    
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

#- task: DotNetCoreCLI@2
#  displayName: Test
 # inputs:
 #   command: test
 #   projects: '$(Parameters.TestProjects)'
 #   arguments: '--configuration $(BuildConfiguration)'

# Publish Pipeline Artifact
# Publish a local directory or file as a named artifact for the current pipeline.
##  displayName: 'Publish Artifact'
#  inputs:
#    PathtoPublish: '$(build.artifactstagingdirectory)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App ServiceApi'
  inputs:
    ConnectedServiceName: 'Visual Studio Enterprise(d2049d9d-1b3e-4047-9440-4c1d065c860f)'
    WebAppKind: 'apiApp'
    WebAppName: exercisetrainingapp


    